//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DooDooDungeon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DooDooDungeon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dungeon_Board {
            get {
                object obj = ResourceManager.GetObject("Dungeon_Board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ErrorSound {
            get {
                return ResourceManager.GetStream("ErrorSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap escapeGrate {
            get {
                object obj = ResourceManager.GetObject("escapeGrate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream FartSound {
            get {
                return ResourceManager.GetStream("FartSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///  &lt;roll&gt;
        ///    &lt;x&gt;169&lt;/x&gt;
        ///    &lt;y&gt;205&lt;/y&gt;
        ///    &lt;Size&gt;40&lt;/Size&gt;
        ///  &lt;/roll&gt;
        ///  &lt;doodoo&gt;
        ///    &lt;x&gt;18&lt;/x&gt;
        ///    &lt;y&gt;446&lt;/y&gt;
        ///    &lt;Size&gt;40&lt;/Size&gt;
        ///  &lt;/doodoo&gt;
        ///  &lt;grate&gt;
        ///    &lt;x&gt;533&lt;/x&gt;
        ///    &lt;y&gt;1&lt;/y&gt;
        ///    &lt;Width&gt;60&lt;/Width&gt;
        ///    &lt;Height&gt;60&lt;/Height&gt;
        ///  &lt;/grate&gt;
        ///  &lt;walls&gt;
        ///    &lt;wall&gt;
        ///      &lt;x&gt;523&lt;/x&gt;
        ///      &lt;y&gt;58&lt;/y&gt;
        ///      &lt;Width&gt;10&lt;/Width&gt;
        ///      &lt;Height&gt;77&lt;/Height&gt;
        ///    &lt;/wall&gt;
        ///    &lt;wall&gt;
        ///      &lt;x&gt;523&lt;/x&gt;
        ///      &lt;y&gt;58&lt;/y&gt;
        ///      &lt;Width&gt;10&lt;/Width&gt;
        ///      &lt;Height&gt;44 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///  &lt;roll&gt;
        ///    &lt;x&gt;19&lt;/x&gt;
        ///    &lt;y&gt;455&lt;/y&gt;
        ///    &lt;Size&gt;40&lt;/Size&gt;
        ///  &lt;/roll&gt;
        ///  &lt;doodoo&gt;
        ///    &lt;x&gt;92&lt;/x&gt;
        ///    &lt;y&gt;134&lt;/y&gt;
        ///    &lt;Size&gt;40&lt;/Size&gt;
        ///  &lt;/doodoo&gt;
        ///  &lt;grate&gt;
        ///    &lt;x&gt;237&lt;/x&gt;
        ///    &lt;y&gt;443&lt;/y&gt;
        ///    &lt;Width&gt;60&lt;/Width&gt;
        ///    &lt;Height&gt;60&lt;/Height&gt;
        ///  &lt;/grate&gt;
        ///	&lt;walls&gt;
        ///		&lt;wall&gt;
        ///			&lt;x&gt;522&lt;/x&gt;
        ///			&lt;y&gt;0&lt;/y&gt;
        ///			&lt;Width&gt;10&lt;/Width&gt;
        ///			&lt;Height&gt;500&lt;/Height&gt;
        ///		&lt;/wall&gt;
        ///		&lt;wall&gt;
        ///			&lt;x&gt;222&lt;/x&gt;
        ///			&lt;y&gt;436&lt;/y&gt;
        ///			&lt;Width&gt;154&lt;/Width&gt;
        ///			&lt;Height&gt;10&lt;/Height&gt;
        ///		&lt;/wall&gt;
        ///		&lt;wal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///  &lt;roll&gt;
        ///    &lt;x&gt;245&lt;/x&gt;
        ///    &lt;y&gt;457&lt;/y&gt;
        ///    &lt;Size&gt;40&lt;/Size&gt;
        ///  &lt;/roll&gt;
        ///  &lt;doodoo&gt;
        ///    &lt;x&gt;17&lt;/x&gt;
        ///    &lt;y&gt;10&lt;/y&gt;
        ///    &lt;Size&gt;40&lt;/Size&gt;
        ///  &lt;/doodoo&gt;
        ///  &lt;grate&gt;
        ///    &lt;x&gt;5&lt;/x&gt;
        ///    &lt;y&gt;440&lt;/y&gt;
        ///    &lt;Width&gt;60&lt;/Width&gt;
        ///    &lt;Height&gt;60&lt;/Height&gt;
        ///  &lt;/grate&gt;
        ///	&lt;walls&gt;
        ///		&lt;wall&gt;
        ///			&lt;x&gt;0&lt;/x&gt;
        ///			&lt;y&gt;57&lt;/y&gt;
        ///			&lt;Width&gt;78&lt;/Width&gt;
        ///			&lt;Height&gt;10&lt;/Height&gt;
        ///		&lt;/wall&gt;
        ///		&lt;wall&gt;
        ///			&lt;x&gt;0&lt;/x&gt;
        ///			&lt;y&gt;181&lt;/y&gt;
        ///			&lt;Width&gt;78&lt;/Width&gt;
        ///			&lt;Height&gt;10&lt;/Height&gt;
        ///		&lt;/wall&gt;
        ///		&lt;wall&gt;
        ///			 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream MoveSound {
            get {
                return ResourceManager.GetStream("MoveSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap New_Piskel__2_ {
            get {
                object obj = ResourceManager.GetObject("New_Piskel__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ThemeSound {
            get {
                return ResourceManager.GetStream("ThemeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Waste_Warroir {
            get {
                object obj = ResourceManager.GetObject("Waste_Warroir", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
